apiVersion: v1
baseDomain: okd.local
metadata:
  name: lab

compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0

controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3

networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
  machineNetwork:
  - cidr: 192.168.0.0/24

platform:
  none: {}

fips: false

pullSecret: '{"auths": ...}' #  Download from https://cloud.redhat.com/openshift/install/pull-secret
sshKey: 'ssh-ed25519 AAAA...'   
