apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs01
provisioner: kubernetes.io/no-provisioner
parameters:
  type: nfs
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
