apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-registry-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /mnt/nfs
    server: 10.20.20.180
  persistentVolumeReclaimPolicy: Retain
